#!/usr/bin/python
import argparse
import json

from config import set_config
from local_deployment import run_local_deployment
from remote_deployment import run_remote_deployment
from validate_arguments import ValidateArguments

CONFIG_FILE = "config.json"

def load_config():
    """Loads config from JSON-file."""
    with open(CONFIG_FILE, "r") as f:
        configuration = json.load(f)
    set_config(configuration)

if __name__ == "__main__":
    load_config()
    # config.validate_config()

    parser = argparse.ArgumentParser(
        description="Deploys and prepares MTA CLI either locally or remotely.")
    parser.add_argument('--mta_version', required=False, help="The MTA version to use.", action=ValidateArguments)
    parser.add_argument('--build', required=False, help="Build number to use", action=ValidateArguments)
    parser.add_argument('--image_output_file', required=False,
                        help='Optional, the file containing related_images for bundle, generated by using get-image-build-details.py')
    parser.add_argument('--dependency_file', required=False,
                        help='Optional, the file containing dependencies to be unpacked in `~/.kantra`')
    parser.add_argument('--ip_address', required=False,
                        help='Optional, IP address of target server where MTA CLI will be deployed')
    parser.add_argument('--upstream', required=False,
                        help='Optional, forces upstream deployment instead of downstream', action=ValidateArguments)

    args = parser.parse_args()

    if not args.ip_address:
        run_local_deployment({"version": args.mta_version,
                              "build": args.build,
                              "args_image_output_file": args.image_output_file,
                              "args_dependency_file": args.dependency_file,
                              "args_upstream": args.upstream
                          })
    else:
        run_remote_deployment({"version": args.mta_version,
                               "build": args.build,
                               "args_image_output_file": args.image_output_file,
                               "args_dependency_file": args.dependency_file,
                               "args_upstream": args.upstream,
                               "args_ip_address": args.ip_address
                          })

